[package]
name = "meowtsun/twig"
description = "A lightweight ECS for Roblox focused on fast queries"
version = "0.1.1"
authors = ["meowtsun"]

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"

[dependencies]
